### ISSUE TITLE
The 'CompaniesRequest' method crashes the application

### ISSUE THREAD

**Issue by kusainovv** [Kirill-Lekhov/ya-business-api#3]
After two pull requests: [this one](https://github.com/Kirill-Lekhov/ya-business-api/pull/1) and [this one](https://github.com/Kirill-Lekhov/ya-business-api/pull/2)

This still doesn't work 👀

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\middleware\exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\starlette\routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\fastapi\routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79085\Desktop\rt-yandex-business-client\main.py", line 19, in root       
    companies_response = api.companies.get_companies(companies_request, raw=False)        
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\ya_business_api\companies\sync_api.py", line 47, in get_companies
    return CompaniesResponse.model_validate_json(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\79085\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\main.py", line 596, in model_validate_json
    return cls.__pydantic_validator__.validate_json(json_data, strict=strict, context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for CompaniesResponse   
listCompanies.0.is_top_rated
  Field required [type=missing, input_value={'id': 66767264311, 'tyco...e}, 'reviewsCount': 114}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
listCompanies.1.is_top_rated
  Field required [type=missing, input_value={'id': 87346211466, 'tyco...e}, 'reviewsCount': 687}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
listCompanies.2.is_top_rated
  Field required [type=missing, input_value={'id': 242866662038, 'tyc...e}, 'reviewsCount': 498}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
listCompanies.3.is_top_rated
  Field required [type=missing, input_value={'id': 197118269639, 'tyc...lse}, 'reviewsCount': 2}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
```

I will be grateful if you figure out what the problem is!

The problem code is:

```python
@app.get("/yandex/companies")
async def root():
    companies_request = CompaniesRequest()
    companies_response = api.companies.get_companies(companies_request, raw=False)
    return companies_response
```

As I understand the Pydantic doesn't exist in API response but Pydantic expects it.

Will it help if **is_top_rated** is **None** ? 

```python
    is_top_rated: Optional[bool] = None
```

**Comment by kusainovv** [comment]
More details:

The first problem was the library doesn't have the 'anonymous review' mechanism. For more details - [right here](https://github.com/Kirill-Lekhov/ya-business-api/pull/1).

The pull request contains a possible solution. The main point to make the '**uid**' and '**avatar**' fields optional.

The pull request was merged and after 1.1.0 release the next code causes the application to crash:

```python
  companies_request = CompaniesRequest()
    companies_response = api.companies.get_companies(companies_request, raw=False)
```

The possible solution was to make 'is_top_rated' optional but the compiler still returns this error.

**Comment by Kirill-Lekhov** [comment]
First of all, please accept my apologies.
I have no way to check the data schema of the undocumented API and reproduce it exactly.

I do not intend to disable strict mode during validation because it helps to catch changes in the API, but you can disable response validation if you do not need it:
```python
companies_request = CompaniesRequest()
raw_companies_response = api.companies.get_companies(companies_request, raw=True)
```

If you still have problems with data validation and you cannot solve them, please send a sample of the data to this address: kirill.lekhov@mail.ru

**Comment by kusainovv** [comment]
Don't worry everything is okay 🙌

I understand your point of view, the ```python raw=True``` really helps! I think the issue is solved!

Thank you!

**Comment by kusainovv** [comment]
Don't worry everything is okay 🙌

I understand your point of view, the 
```python 
raw=True
``` 

really helps! I think the issue is solved!

Thank you!
